name: suns
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7.8
  - pip
  - numpy = 1.17.5
  - h5py = 2.8.0
  - matplotlib = 3.1.2
  - numba = 0.52.0 
  - opencv = 3.4.1
  - scikit-image = 0.16.2 
  - scikit-learn = 0.21.2 
  - scipy = 1.3.2
  - shapely = 1.6.4 
  # - tensorflow = 1.15
  - tensorflow-gpu = 1.15
  - keras = 2.2.4 
  - pip:
    - fissa == 0.7.2
    - pyfftw == 0.11.1 
    - tensorflow-estimator == 1.15.1
    - py-cpuinfo == 7.0.0
