name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.3
  - argh=0.26.2
  - asn1crypto=1.3.0
  - astor=0.7.1
  - astroid=2.3.3
  - astropy=4.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.5
  - babel=2.8.0
  - backcall=0.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.1.7
  - beautifulsoup4=4.8.2
  - bitarray=1.2.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.17.0
  - bokeh=1.4.0
  - boto=2.49.0
  - bottleneck=1.3.1
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.2
  - clyent=1.2.2
  - colorama=0.4.3
  - comtypes=1.1.7
  - conda=4.9.2
  - conda-build=3.18.11
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contextlib2=0.6.0.post1
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - curl=7.65.3
  - cycler=0.10.0
  - cython=0.29.14
  - cytoolz=0.10.1
  - dask=2.9.2
  - dask-core=2.9.2
  - decorator=4.4.1
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - dill=0.3.1.1
  - distributed=2.9.3
  - docutils=0.16
  - entrypoints=0.3
  - enum34=1.1.6
  - et_xmlfile=1.0.1
  - fastcache=1.1.0
  - filelock=3.0.10
  - flake8=3.7.9
  - flask=1.1.1
  - freetype=2.10.0
  - fsspec=0.6.2
  - future=0.18.2
  - gast=0.2.2
  - geos=3.8.0
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - git=2.23.0
  - glob2=0.7
  - google-pasta=0.1.8
  - greenlet=0.4.15
  - grpcio=1.23.0
  - h5py=2.8.0
  - hdf5=1.10.2
  - hdmf=1.3.3
  - heapdict=1.0.1
  - html5lib=1.0.1
  - hypothesis=5.3.0
  - icc_rt=2019.0.0
  - icu=64.2
  - idna=2.8
  - imagecodecs-lite=2019.12.3
  - imageio=2.6.1
  - imagesize=1.2.0
  - importlib_metadata=1.4.0
  - intel-openmp=2019.4
  - intervaltree=3.0.2
  - ipykernel=5.1.3
  - ipython=7.10.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.14.1
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.5
  - jupyterlab_server=1.0.6
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - keyring=21.1.0
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.65.3
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.9.0
  - libopencv=3.4.1
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvmlite=0.35.0
  - locket=0.2.0
  - lxml=4.4.2
  - lz4-c=1.8.3
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mccabe=0.6.1
  - menuinst=1.4.16
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - more-itertools=8.1.0
  - mpmath=1.1.0
  - msgpack-python=0.6.2
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - multiprocess=0.70.9
  - navigator-updater=0.2.1
  - nbconvert=5.6.1
  - nbformat=5.0.3
  - networkx=2.4
  - nltk=3.4.4
  - nose=1.3.7
  - notebook=6.0.3
  - numba=0.52.0
  - numexpr=2.7.1
  - numpy=1.17.5
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - opencv=3.4.1
  - openpyxl=3.0.3
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - packaging=20.0
  - pandas=0.25.3
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - paramiko=2.7.1
  - parso=0.5.2
  - partd=1.1.0
  - path=13.1.0
  - path.py=12.4.0
  - pathlib=1.0.1
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.3.1
  - pkginfo=1.5.0.1
  - pluggy=0.12.0
  - ply=3.11
  - powershell_shortcut=0.0.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.11.2
  - psutil=5.6.7
  - py=1.8.1
  - py-lief=0.9.0
  - py-opencv=3.4.1
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.4
  - pydocstyle=5.0.2
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pylint=2.4.4
  - pynacl=1.3.0
  - pynwb=1.0.2
  - pyodbc=4.0.28
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pyreadline=2.1
  - pyrsistent=0.14.11
  - pysocks=1.7.1
  - pytables=3.4.4
  - pytest=5.3.4
  - pytest-arraydiff=0.3
  - pytest-astropy=0.7.0
  - pytest-astropy-header=0.1.2
  - pytest-doctestplus=0.4.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.1
  - python=3.7.5
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.7
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2019.3
  - pywavelets=1.1.1
  - pywin32=225
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qdarkstyle=2.7
  - qt=5.12.5
  - qtawesome=0.6.1
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - requests=2.22.0
  - requests-toolbelt=0.9.1
  - rope=0.16.0
  - rtree=0.9.3
  - ruamel.yaml=0.16.6
  - ruamel.yaml.clib=0.2.0
  - ruamel_yaml=0.15.80
  - scikit-image=0.16.2
  - scikit-learn=0.21.2
  - scipy=1.3.2
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=45.1.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - simplejson=3.17.0
  - singledispatch=3.4.0.3
  - sip=4.19.20
  - six=1.14.0
  - snappy=1.1.8
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.4
  - sphinx=2.3.1
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sphinxcontrib-websupport=1.1.2
  - spyder=4.0.1
  - spyder-kernels=1.8.1
  - sqlalchemy=1.3.12
  - sqlite=3.30.1
  - statsmodels=0.11.0
  - sympy=1.5.1
  - tblib=1.6.0
  - tensorboard=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tifffile=2019.7.26.2
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.41.1
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - ujson=1.35
  - unicodecsv=0.14.1
  - urllib3=1.25.7
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - watchdog=0.9.0
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.2.7
  - xlwings=0.17.0
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.2.2
  - yapf=0.28.0
  - zeromq=4.3.2
  - zict=1.0.0
  - zipp=2.0.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - fissa==0.6.1
    - holoviews==1.12.7
    - imagecodecs==2019.12.16
    - line-profiler==3.0.2
    - matlab==0.1
    - matlabengineforpython==R2018a
    - memory-profiler==0.57.0
    - neurofinder==1.1.1
    - nibabel==3.0.0
    - param==1.9.2
    - py-cpuinfo==7.0.0
    - pyfftw==0.11.1
    - pympler==0.8
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyviz-comms==0.7.2
    - regional==1.1.2
    - tensorflow==1.13.2
    - tensorflow-gpu==1.13.2
    - tuncat==1.0.3
